config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :users, only: [:index, :show]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  root to: "home#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: :favorited, source_type: 'User'

  acts_as_messageable

  def mailboxer_email(object)
      email
  end

  has_attached_file :picture,
                    :default_url => "/images/original/missing.png",
                    :styles => {
                      :thumb    => ['100x100#',  :jpg, :quality => 70],
                      :preview  => ['480x480#',  :jpg, :quality => 70],
                      :large    => ['600>',      :jpg, :quality => 70],
                      :retina   => ['1200>',     :jpg, :quality => 30]},
                    :convert_options => {
                      :thumb    => '-set colorspace sRGB -strip',
                      :preview  => '-set colorspace sRGB -strip',
                      :large    => '-set colorspace sRGB -strip',
                      :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'}
  validates_attachment :picture,
                       :presence => true,
                       :size => { :in => 0..10.megabytes },
                       :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  rescue_from ActiveRecord::RecordNotFound do
    flash[:warning] = 'Resource not found.'
    redirect_back_or root_path
  end

  def redirect_back_or(path)
    redirect_to request.referer || path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit :first_name, :last_name, :email, :password, :password_confirmation,
      :sex, :seeking_sex_type, :birthday, :country, :city, :agree_to_terms
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit :first_name, :last_name, :email, :password, :password_confirmation,
      :seeking_sex_type, :country, :city, :current_password, :height, :weight,
      :ethnicity, :drink, :smoke, :marital_status, :children, :number_of_children,
      :want_children, :occupation, :employment_status, :education, :religion,
      :religious_values, :profile_heading, :user_profile, :picture
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user
    @current_user = current_user
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def new
    @chosen_recipient = User.find_by(id: params[:to].to_i) if params[:to]
  end

  def create
    recipients = User.where(id: params['recipients'])
    conversation = current_user.send_message(recipients, params[:message][:body], params[:message][:subject]).conversation
    flash[:success] = "Message has been sent!"
    redirect_to conversation_path(conversation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.order('created_at DESC').paginate(page: params[:page], per_page: 30)
  end

  def show
    @user = User.find(params[:id])
  end

private
  # def user_params
  #   params.require(:user).permit(:username, :email, :password, :password_confirmation)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_header(text)
    content_for(:page_header) { text.to_s }
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options(chosen_recipient = nil)
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}'>#{user.first_name}</option>"
    end
    s.html_safe
  end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation) %>

  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
      <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
    <% else %>
      <%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
                  data: {confirm: 'Are you sure?'} %>

      <% if conversation.is_unread?(current_user) %>
        <%= link_to 'Mark as read', mark_as_read_conversation_path(conversation),
                    class: 'btn btn-xs btn-info', method: :post %>
      <% end %>
    <% end %>
  </div>

  <p><%= render 'conversations/participants', conversation: conversation %></p>

  <p><%= conversation.last_message.body %>
    <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<% page_header "Your Conversations" %>

<p><%= link_to 'Start conversation', new_message_path, class: 'btn btn-lg btn-primary' %></p>

<div class="row">
  <div class="col-sm-3">
    <ul class="nav nav-pills nav-stacked">
      <%= mailbox_section 'inbox', @box %>
      <%= mailbox_section 'sent', @box %>
      <%= mailbox_section 'trash', @box %>
    </ul>
  </div>

  <div class="col-sm-9">
    <% if @box == 'trash' %>
      <p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
                     data: {confirm: 'Are you sure?'} %></p>
    <% end %>
    <ul class="list-group">
      <%= render partial: 'conversations/conversation', collection: @conversations %>
    </ul>

    <%= will_paginate %>
  </div>
</div>

app/views/conversations/show.html.erb
<% page_header "Conversation" %>

<p>Chatting with
  <%= render 'conversations/participants', conversation: @conversation %>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><%= @conversation.subject %></div>

  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <div class="media">
          <% message = receipt.message %>
          <div class="media-left">

          </div>

          <div class="media-body">
            <h6 class="media-heading"><%= message.sender.first_name %>
              says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
            <%= message.body %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= form_tag reply_conversation_path(@conversation), method: :post do %>
  <div class="form-group">
    <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
  </div>
  <%= submit_tag "Send Message", class: 'btn btn-primary' %>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to Personally</h1>

<% if @user != nil %>
  Hello <%= @user.first_name %> <%= @user.birthday %>

  <%= link_to "View Your Profile", user_path(@user) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Personally</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Personally', root_path, class: 'navbar-brand' %>
      </div>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Your Conversations', conversations_path %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>

    <div class="page-header">
      <h1><%= yield :page_header %></h1>
    </div>

    <%= yield %>

  </div>

  <footer>
    <div class="container">
      <p class="text-muted">Created by <a href="http://www.github.com/datureezy" target="_blank">Ron Park aka datureezy</a>.</p>
    </div>
  </footer>

</body>
</html>

app/views/messages/new.html.erb
<% page_header "Start Conversation" %>

<%= form_tag messages_path, method: :post do %>
  <div class="form-group">
    <%= label_tag 'message[subject]', 'Subject' %>
    <%= text_field_tag 'message[subject]', nil, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= label_tag 'message[body]', 'Message' %>
    <%= text_area_tag 'message[body]', nil, cols: 3, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= label_tag 'recipients', 'Choose recipients' %>
    <%= select_tag 'recipients', recipients_options(@chosen_recipient), multiple: true, class: 'form-control chosen-it' %>
  </div>

  <%= submit_tag 'Send', class: 'btn btn-primary' %>
<% end %>

app/views/users/index.html.erb
<% page_header "Users" %>

<%= will_paginate %>

<ul>
  <% @users.each do |user| %>
    <li>
      <strong><%= user.first_name %></strong>
      <% unless current_user == user %>
        <%= link_to 'Send message', new_message_path(to: user.id), class: 'btn btn-default btn-sm' %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<h1><%= @user.first_name %></h1>
<h2><%= @user.city %>, <%= @user.country %> - <%= @user.sex %></h2>
<h3>ID #<%= @user.id %></h3>
<h4>Seeking: <%= @user.seeking_sex_type %>s</h4>
<h4>Last Active: <%= @user.last_sign_in_at %></h4>

<p>
  <%= image_tag @user.picture.url(:thumb) %>
</p>

<%- unless current_user.favorite_users.exists?(id: @user.id) -%>
<%= link_to 'Add to favorites', favorite_users_path(favorited_id: @user), method: :post %>
<%- else -%>
<%= link_to 'Remove from favorites', favorite_user_path(@user), method: :delete %>
<%- end -%>

<ul>
  <li>Height: <% if @user.height != nil %>
                    <%= @user.height %>cm
                 <% else %>
                    N/A
                 <% end %></li>

  <li>Weight: <% if @user.weight != nil %>
                    <%= @user.weight %>KG
                 <% else %>
                    N/A
                 <% end %></li>

  <li>Ethnicity: <% if @user.ethnicity != nil %>
                    <%= @user.ethnicity %>
                 <% else %>
                    N/A
                 <% end %></li>

  <li>Marital Status: <% if @user.marital_status != nil %>
                    <%= @user.marital_status %>
                 <% else %>
                    N/A
                 <% end %></li>

  <li>Number of Children: <% if @user.number_of_children != nil %>
                    <%= @user.number_of_children %>
                 <% else %>
                    N/A
                 <% end %></li>

  <li>Occupation: <% if @user.occupation != nil %>
                    <%= @user.occupation %>
                 <% else %>
                    N/A
                 <% end %></li>

  <li>Employment Status: <% if @user.employment_status != nil %>
                    <%= @user.employment_status %>
                 <% else %>
                    N/A
                 <% end %></li>

  <li>Education: <% if @user.education != nil %>
                    <%= @user.education %>
                 <% else %>
                    N/A
                 <% end %></li>

  <li>Religion: <% if @user.religion != nil %>
                    <%= @user.religion %>
                 <% else %>
                    N/A
                 <% end %></li>

  <li>Religious Values: <% if @user.religious_values != nil %>
                    <%= @user.religious_values %>
                 <% else %>
                    N/A
                 <% end %></li>

  <li>Do Drink?: <% if @user.drink != nil %>
                    <%= @user.drink %>
                 <% else %>
                    N/A
                 <% end %></li>

  <li>Do Smoke?: <% if @user.smoke != nil %>
                    <%= @user.smoke %>
                 <% else %>
                    N/A
                 <% end %></li>
</ul>

<h1><%= @user.profile_heading %></h1>

<h1>User Profile:<br></h1>
<%= @user.user_profile %>